### ISSUE TITLE
Npm install fails

### ISSUE THREAD

**Issue by AshHeskes** [jacobrask/styledocco#68] opened 2013-02-21 12:54 UTC
```
Running "browserify:dist/docs.js" (browserify) task

Error: Cannot find module: "async" from directory "/Users/Ash/Projects/styledocco/web" while processing file /Users/Ash/Projects/styledocco/web/app.js
    at moduleError (/Users/Ash/Projects/styledocco/node_modules/grunt-browserify/node_modules/browserify/lib/wrap.js:422:16)
    at Function.Wrap.require (/Users/Ash/Projects/styledocco/node_modules/grunt-browserify/node_modules/browserify/lib/wrap.js:461:19)
    at Function.module.exports.Object.keys.forEach.self.(anonymous function) [as require] (/Users/Ash/Projects/styledocco/node_modules/grunt-browserify/node_modules/browserify/index.js:158:28)
    at Wrap.addEntry (/Users/Ash/Projects/styledocco/node_modules/grunt-browserify/node_modules/browserify/lib/wrap.js:239:14)
    at Array.forEach (native)
    at Function.Wrap.addEntry (/Users/Ash/Projects/styledocco/node_modules/grunt-browserify/node_modules/browserify/lib/wrap.js:231:22)
    at Function.module.exports.Object.keys.forEach.self.(anonymous function) [as addEntry] (/Users/Ash/Projects/styledocco/node_modules/grunt-browserify/node_modules/browserify/index.js:158:28)
    at /Users/Ash/Projects/styledocco/node_modules/grunt-browserify/tasks/browserify.js:39:9
    at Array.forEach (native)
    at Object.module.exports (/Users/Ash/Projects/styledocco/node_modules/grunt-browserify/tasks/browserify.js:37:53)
npm ERR! styledocco@0.7.0alpha prepublish: `grunt`
npm ERR! `sh "-c" "grunt"` failed with 1
npm ERR! 
npm ERR! Failed at the styledocco@0.7.0alpha prepublish script.
npm ERR! This is most likely a problem with the styledocco package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt
npm ERR! You can get their info via:
npm ERR!     npm owner ls styledocco
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 12.2.1
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/Ash/Projects/styledocco
npm ERR! node -v v0.8.17
npm ERR! npm -v 1.2.0
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Ash/Projects/styledocco/npm-debug.log
npm ERR! not ok code 0
```

**Comment by marrs** [comment] 2013-06-25 00:36
npm install works for me without the patch, installing against master.  Is this still an issue for you both?

**Comment by marrs** [comment] 2013-06-28 10:49
Closing as I can't reproduce. Please reopen if it's still an issue for you

**Closed as completed by marrs** 2013-06-28 10:49 UTC
