### ISSUE TITLE
Parsing multiple css files

### ISSUE THREAD

**Issue by wooooow** [jacobrask/styledocco#28] opened 2012-06-04 14:15 UTC
Hi,

I'm running Styledocco on Windows with node.js.

When I type the following:

styledocco -n "MyProject" css  

*css is a folder with styles.css & styles2.css

Styledocco only parses styles.css but I want both of my files in the StyleGuide.

What should I do?

Thanks

**Comment by wooooow** [comment] 2012-06-06 08:25
It works fine with Ubuntu but I really need it to work on Windows.

Thx

**Comment by jacobrask** [comment] 2012-06-27 20:47
Thank you for your report, I have now done some changes to the way StyleDocco handles input files. Can you try if it works with StyleDocco 0.4.0?

**Comment by wooooow** [comment] 2012-06-29 09:32
It still not working.

I've updated styledocco and when I type the same command.
It only parses one of my files.

**Comment by morewry** [comment] 2012-11-15 20:35
I also have this issue on Windows (styledocco 0.6.1)

**Comment by somecallmejosh** [comment] 2013-02-23 02:36
I'm experiencing the same issue with 0.6.1.

**Comment by ghost** [comment] 2013-04-19 13:53
I'm experiencing the same issue on Windows 8.

The command I'm using is this:
styledocco -n "My project" -o mydocs styles --verbose

the output is:
styledocco: writing styles/grid.less -> mydocs\grid.html
styledocco: writing D:\Work\Projects\NP\styles\index -> mydocs\index.html

I was expecting:
styledocco: writing styles/grid.less -> mydocs\grid.html
styledocco: writing styles/ui.less -> mydocs\ui.html
styledocco: writing styles/**_.less -> mydocs\**_.html
...
styledocco: writing D:\Work\Projects\styles\index -> mydocs\index.html

**Comment by marrs** [comment] 2013-06-29 18:03
Closing as I can't reproduce. It's not related to issue #64 as I'd hypothesised.

**Closed as completed by marrs** 2013-06-29 18:03 UTC
Labels: bug
